steps:
- name: 'golang:1.23'
  args: ['go', 'build', '-o', 'warehousecli']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'warehousecli', 'gs://bw-apt']

- name: 'golang:1.23'
  args: ['goreleaser']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'dist/', 'gs://bw-apt']
