steps:
  - name: 'golang:1.23'
    args:
      - go
      - build
      - '-o'
      - warehousecli
    dir: warehousecli
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - warehousecli/warehousecli
      - 'gs://bw-apt'
  - name: 'ubuntu:latest'
    args:
      - bash
      - '-c'
      - |
        set -e
        apt-get update -y
        apt-get install -y dpkg fakeroot
        ./warehousecli/build/build.sh
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - ./dist/warehouse.deb
      - 'gs://bw-apt'
