steps:
  - name: 'golang:1.23'
    args:
      - go
      - build
      - '-o'
      - warehousecli
    dir: warehousecli
  - name: 'ubuntu:latest'
    args:
      - bash
      - '-c'
      - |
        set -e
        apt-get update -y
        apt-get install -y dpkg fakeroot
        ./warehousecli/build/build.sh "${TAG_NAME}"
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - ./dist/warehousecli.deb
      - 'gs://${_BUCKET_NAME}'
