steps:
  - name: 'golang:1.23'
    args:
      - go
      - build
      - '-o'
      - warehousecli
    dir: warehousecli

  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - warehousecli/warehousecli
      - 'gs://bw-apt'

  - name: 'ubuntu:latest'
    args:
    - ./build/build.sh
  - name: gcr.io/cloud-builders/gsutil
    args:
      - cp
      - ./build/dist/debian
      - 'gs://bw-apt'
