version: 2.1

jobs:
    test-products-api:
        docker:
            - image: cimg/go:1.22.0
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: cd ./products-api && go mod tidy
            - run:
                  name: Run the tests
                  command: cd ./products-api && go test ./...

workflows:
    test:
        jobs:
            - test-products-api
