version: 2.1

jobs:
    test-products:
        docker:
            - image: cimg/go:1.21.1
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: cd ./products && go mod tidy
            - run:
                  name: Run the tests
                  command: cd ./products && go test ./...

workflows:
    test:
        jobs:
            - test-products
